name: oci-builds

on:
  push:
    branches: [ main ]
    tags:        
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build-qenvs-packer-windows :
    name: build-qenvs-builder-aws-windows
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pick image tag on non pull-request
      if: github.event_name != 'pull_request'
      shell: bash
      run: echo "TAG=${{ GITHUB.REF_NAME}}" >> $GITHUB_ENV

    - name: Pick image tag on pull-request
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "TAG=${{ GITHUB.EVENT.PULL_REQUEST.HEAD.REF}}" >> $GITHUB_ENV

    - name: Build image
      id: build-image
      uses: redhat-actions/buildah-build@v2.10
      with:
        image: qenvs-builder
        tags: ${{ env.TAG }}-aws-windows
        context: aws
        containerfiles: |
          aws/windows/oci/Containerfile

    - name: Log in to quay.io Registry
      uses: redhat-actions/podman-login@v1.4
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_IO_USERNAME }}
        password: ${{ secrets.QUAY_IO_PASSWORD }}

    - name: Push to quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2.6
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/rhqp

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"

  