FROM docker.io/hashicorp/packer:1.10

WORKDIR /workspace
# context is packer folder
COPY windows/aws .

RUN apk add --update curl aws-cli jq \
    && mv oci/entrypoint.sh /usr/local/bin

ENTRYPOINT entrypoint.sh


